### ISSUE TITLE
This check is redundant with check in addHelper

### ISSUE THREAD

**Issue by slobacartoonac** [axecopfire/interview_prep#1]
https://github.com/axecopfire/interview_prep/blob/79e5d983542943925173c8ad2725a15dcd410fd7/feMasters/4semesters/ex/DataStructure/AVL.js#L13
Maube you should remove it.

**Comment by axecopfire** [comment]
Updated in 78856053f3808620c0154b648294f7c5df042068

**Comment by slobacartoonac** [comment]
By the way, good work on the lib :)
